version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - opensearch
      - redis
    env_file:
      - .env
    networks:
      - bot_network

  opensearch:
    image: "opensearchproject/opensearch"
    environment:
      - cluster.name=my-opensearch-cluster
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - bot_network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  opensearch_data:
  redis_data:
